### ISSUE TITLE
Add interface to exit component and signal exit status

### ISSUE THREAD

**Issue by senier** [Componolit/ada-interface#34]
Components may wish to exit and signal a result of their execution to the platform. Add a platform interface to exit a component and to signal the exit status.

**Comment by jklmnn** [comment]
Instead of exiting instantly the platform provides a `Vacate` procedure that tells the platform to call a `Destruct` procedure which enables the component to finalize all sessions. It then exits the component.

**Comment by jklmnn** [comment]
Fixed by #57.
