### ISSUE TITLE
Platform specification Linux/Posix

### ISSUE THREAD

**Issue by jklmnn** [Componolit/ada-interface#51]
The implementations of block and configuration client on posix raised obscurities about the distinction of the posix/Linux platforms. The current posix implementation is a C implementation based on libc that uses standard posix mechanisms. Although parts of the code are Linux specific and will most probably not compile on other platforms. This raises the issue if posix is the correct platform definition.

I see three ways to solve this issue:

 1. rename posix to linux
 2. implement platform generic mechanisms
 3. divide posix into more platforms with a large shared code base

Some ideas:

1. This is probably the easiest option. But it would collide with an eventual in kernel implementation which then also would be called linux.
2. Since all the code runs on posix conform platforms with posix conform build systems/compilers abstraction layers that provide implementations for different platforms could be embedded without changing the public interface of the posix platform for the CAI build system. In detail this means wrappers around the problematic code (in this case inotify and block size detection) that provided different implementations for different posix platforms which are selected via macros. These implementations could then be extended easily for new posix compatible platforms.
3. Basically like 2. but instead of macros the distinction is done via the CAI build system. Each posix directory would have a subdirectory for Linux/BSD etc. if necessary.

Personally I prefer 2.

**Comment by senier** [comment]
Let's rename the platform to `linux` for user-space linux applications. For the potential Linux kernel support we will find another name later (this may be longer, as code running in the Linux kernel is unexpected to the user anyway). Should MacOS/BSD support ever become an issue, we will integrate it into the `linux` codebase using defines.
